// Re-export from new location for backward compatibility

// Auction Types (re-export from new location for backward compatibility)
export type {
  AuctionDiskData,
  AuctionFilterOptions,
  AuctionIpPrice,
  AuctionResponse,
  AuctionServer,
} from "./auction/types.js";
export type {
  ApiError,
  ApiResponse,
  BootConfig,
  Cancellation,
  CpanelConfig,
  Failover,
  Firewall,
  FirewallRule,
  FirewallTemplate,
  IP,
  LinuxConfig,
  Mac,
  PleskConfig,
  ProductPrice,
  Rdns,
  RescueConfig,
  Reset,
  ResetType,
  Server,
  ServerDetails,
  ServerMarketProduct,
  ServerProduct,
  ServerSubnet,
  ServerTransaction,
  ServerTransactionProduct,
  SshKey,
  StorageBox,
  StorageBoxSnapshot,
  StorageBoxSnapshotPlan,
  StorageBoxSubaccount,
  Subnet,
  Traffic,
  TrafficData,
  VncConfig,
  VSwitch,
  VSwitchCloudNetwork,
  VSwitchServer,
  VSwitchSubnet,
  WindowsConfig,
  Wol,
} from "./robot/types.js";
